import {
  AlertTriangle,
  ArrowRight,
  BookMarked,
  Building,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  LucideProps,
  Menu,
  Moon,
  MoreVertical,
  Phone,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  User,
  X
} from 'lucide-react';
import { AiFillStar } from 'react-icons/ai';
import { BiLaugh, BiSolidUser } from 'react-icons/bi';
import { BsInfoCircle, BsQuestionCircle } from 'react-icons/bs';
import {
  HiBriefcase,
  HiOutlineExternalLink,
  HiOutlineLink
} from 'react-icons/hi';
import { IoIosGitBranch } from 'react-icons/io';
import {
  SiAdobephotoshop,
  SiAdobexd,
  SiAmazonaws,
  SiAngular,
  SiAnsible,
  SiBabel,
  SiBitbucket,
  SiBootstrap,
  SiBun,
  SiCss3,
  SiCypress,
  SiDjango,
  SiDocker,
  SiEslint,
  SiExpress,
  SiFigma,
  SiFirebase,
  SiFlask,
  SiGit,
  SiGithub,
  SiGitlab,
  SiGmail,
  SiGnubash,
  SiGooglecloud,
  SiGraphql,
  SiHtml5,
  SiIntellijidea,
  SiJavascript,
  SiJenkins,
  SiJest,
  SiKubernetes,
  SiLinkedin,
  SiLinux,
  SiMicrosoftazure,
  SiMongodb,
  SiMui,
  SiMysql,
  SiNestjs,
  SiNetlify,
  SiNextdotjs,
  SiNodedotjs,
  SiNpm,
  SiPostgresql,
  SiPowershell,
  SiPrettier,
  SiPuppeteer,
  SiPython,
  SiReact,
  SiRedis,
  SiRedux,
  SiSelenium,
  SiSocketdotio,
  SiTailwindcss,
  SiTerraform,
  SiTwitter,
  SiTypescript,
  SiVercel,
  SiVisualstudiocode,
  SiWebpack,
  SiWordpress,
  SiYarn
} from 'react-icons/si';
import {
  SiPrisma,
  SiFramer,
  SiVite,
  SiReactrouter
} from 'react-icons/si';
import { FaBullhorn } from 'react-icons/fa';
import { BiLayer } from 'react-icons/bi';
import { RiLockPasswordLine } from 'react-icons/ri';
import { BsShieldLock, BsCheckCircleFill } from 'react-icons/bs';
import { TbChartBar, TbRoute } from 'react-icons/tb';

export const Icons = {
  contact: Phone,
  gitRepoIcon: BookMarked,
  gitOrgBuilding: Building,
  gitBranch: IoIosGitBranch,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  menu: Menu,
  chevronDown: ChevronDown,
  laughEmoji: BiLaugh,
  check: Check,
  infoMark: BsInfoCircle,
  questionMark: BsQuestionCircle,
  link: HiOutlineLink,
  externalLink: HiOutlineExternalLink,
  star: AiFillStar,
  amazonaws: SiAmazonaws,
  angular: SiAngular,
  bootstrap: SiBootstrap,
  css3: SiCss3,
  express: SiExpress,
  graphql: SiGraphql,
  html5: SiHtml5,
  javascript: SiJavascript,
  mongodb: SiMongodb,
  mui: SiMui,
  mysql: SiMysql,
  nestjs: SiNestjs,
  netlify: SiNetlify,
  nextjs: SiNextdotjs,
  nodejs: SiNodedotjs,
  react: SiReact,
  redux: SiRedux,
  socketio: SiSocketdotio,
  tailwindcss: SiTailwindcss,
  typescript: SiTypescript,
  gmail: SiGmail,
  twitter: SiTwitter,
  linkedin: SiLinkedin,
  userFill: BiSolidUser,
  work: HiBriefcase,
  python: SiPython,
  django: SiDjango,
  flask: SiFlask,
  docker: SiDocker,
  kubernetes: SiKubernetes,
  aws: SiAmazonaws,
  azure: SiMicrosoftazure,
  gcp: SiGooglecloud,
  git: SiGit,
  github: SiGithub,
  gitlab: SiGitlab,
  bitbucket: SiBitbucket,
  jenkins: SiJenkins,
  terraform: SiTerraform,
  ansible: SiAnsible,
  linux: SiLinux,
  bash: SiGnubash,
  powershell: SiPowershell,
  vscode: SiVisualstudiocode,
  intellij: SiIntellijidea,
  postgresql: SiPostgresql,
  redis: SiRedis,
  jest: SiJest,
  cypress: SiCypress,
  selenium: SiSelenium,
  puppeteer: SiPuppeteer,
  webpack: SiWebpack,
  babel: SiBabel,
  eslint: SiEslint,
  prettier: SiPrettier,
  npm: SiNpm,
  vercel: SiVercel,
  firebase: SiFirebase,
  figma: SiFigma,
  adobeXd: SiAdobexd,
  photoshop: SiAdobephotoshop,
  wordpress: SiWordpress,
  yarn: SiYarn,
  bun: SiBun,
  gitHub: SiGithub,
  successAnimated: BsCheckCircleFill,
  prisma: SiPrisma,
  framer: SiFramer,
  vite: SiVite,
  reactrouter: SiReactrouter,
  tanstack: TbRoute,
  recharts: TbChartBar,
  bull: FaBullhorn,
  passport: RiLockPasswordLine,
  jwt: BsShieldLock,
  shadcn: BiLayer,
};
