export type ValidSkills =
  | 'Next.js'
  | 'React'
  | 'express.js'
  | 'Node.js'
  | 'MongoDB'
  | 'Typescript'
  | 'Javascript'
  | 'HTML 5'
  | 'CSS 3'
  | 'Next.js 14'
  | 'Prisma ORM'
  | 'Redux Toolkit'
  | 'React Router Dom'
  | 'Framer Motion'
  | 'Shadcn UI'
  | 'Redux'
  | 'Socket.io'
  | 'Material UI'
  | 'Tailwind CSS'
  | 'AWS'
  | 'Bootstrap'
  | 'Google Auth'
  | 'MySQL'
  | 'Docker'
  | 'Kubernetes'
  | 'Git'
  | 'GitHub'
  | 'CI/CD'
  | 'Vercel'
  | 'Vite'
  | 'PHP'
  | 'WordPress'
  | 'Redux Toolkit'
  | 'TanStack Router'
  | 'Recharts'
  | 'Express.js'
  | 'Redis'
  | 'Socket.IO'
  | 'AWS S3'
  | 'AWS SES'
  | 'AWS SNS'
  | 'Bull Queue'
  | 'JWT'
  | 'Passport.js';

export type ValidCategory =
  | 'Full Stack'
  | 'E-commerce'
  | 'Frontend'
  | 'Frontend Dev'
  | 'Backend'
  | 'UI/UX'
  | 'Web Dev'
  | 'Web Development';

export type ValidExpType = 'Personal Project' | 'Professional';

export type ValidPages =
  | 'home'
  | 'skills'
  | 'projects'
  | 'experience'
  | 'contact'
  | 'contributions'
  | 'resume';
