export const siteConfig = {
  name: 'Swapnil Mahadik Portfolio',
  authorName: 'Swapnil Mahadik',
  username: 'swapnilMk',
  email: 'mswapnil218@gmail.com',
  role: [
    'Full Stack Developer',
    'Frontend Developer',
    'Backend Developer',
    'UI/UX Designer',
    'Web Engineer',
    'Software Developer',
    'Creative Coder',
    'Technical Lead',
    'DevOps Specialist',
    'SEO Expert',
    'Accessibility Advocate',
    'Performance Engineer',
    'Cloud Architect',
    'API Designer',
    'Component Library Author',
    'Mentor & Speaker',
    'Open Source Contributor',
    'Test Automation Engineer',
    'System Reliability Engineer',
    'Product-focused Engineer'
  ],
  heading: `Passionate about creating 
            impactful web experiences`,
  description: `With over 2 years of experience in full-stack development, I design and build scalable, maintainable web applications using modern technologies and best practices.
  
  I focus on delivering great user experiences by combining strong frontend engineering (React, Next.js, TypeScript) with robust backend solutions (Node.js, REST/GraphQL), cloud deployments, and CI/CD automation. I enjoy tackling performance and accessibility challenges and mentoring other developers.

  Outside of hands-on coding, I contribute to open source, write technical articles, and speak at community meetups to share practical lessons and patterns for building production-ready web apps.`,
  url: 'https://swapnil-portfolioweb.vercel.app/',
  cv: '/resume.pdf',
  ogImage: 'https://swapnil-portfolioweb.vercel.app/',
  iconIco:
    'https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357384/assets/naman-favicon.ico',
  logoIcon:
    'https://res.cloudinary.com/dbfvcn3f6/image/upload/v1692357294/assets/naman-logo.png',
  location: 'Pune, India',
  contactEmail: 'swapnil@example.com',
  social: {
    github: 'https://github.com/swapnilMk',
    linkedin: 'https://www.linkedin.com/in/swapnil-mahadik',
    twitter: 'https://twitter.com/swapnilMk',
    dribbble: 'https://dribbble.com/swapnilMk'
  },
  keywords: [
    'Swapnil Mahadik',
    'Swapnil Mahadik Portfolio',
    'Swapnil Mahadik Projects',
    'Swapnil Mahadik Experience',
    'Swapnil Mahadik Resume',
    'Next.js',
    'React',
    'TypeScript',
    'Tailwind CSS',
    'Server Components',
    'Radix UI',
    'Shadcn',
    'Next SEO',
    'Node.js',
    'Express',
    'GraphQL',
    'Prisma',
    'Postgres',
    'Docker',
    'Kubernetes',
    'AWS',
    'Vercel',
    'Performance Optimization',
    'Accessibility',
    'Web Architecture',
    'Component Library',
    'Open Source',
    'Mentoring',
    'Technical Writing',
    'Frontend Engineer',
    'Backend Engineer',
    'Full Stack Developer',
    'DevOps',
    'CI/CD',
    'SEO',
    'UI/UX',
    'Design Systems',
    'Testing',
    'Automation'
  ]
};
